### ISSUE TITLE
Grafiklerin tarih bilgileri Türkçeye çevirilmeli

### ISSUE THREAD

**Issue by ozanerturk** [ozanerturk/covid19-turkey-api#1]
Yataydaki ay bilgileri türkçeye çevirilmeli
![image](https://user-images.githubusercontent.com/15703627/78713901-a3f85a80-7923-11ea-84ac-898cc29b83d0.png)

**Comment by berkekurnaz** [comment]
Chart ayarlarını aşağıdaki gibi güncellersen bu sorun çözülecek gibi duruyor.
Ayrıntılı Döküman: [Döküman](https://apexcharts.com/docs/options/chart/locales/)
`chart: {
  defaultLocale: 'tr',
  locales: [{
    name: 'tr',
    options: {
      months: ['Ocak', 'Şubat', 'Mart', 'Nisan', 'Mayıs', 'Haziran', 'Temmuz', 'Ağustos', 'Eylül', 'Ekim', 'Kasım', 'Aralık'],
      shortMonths: ['Ock', 'Şbt', 'Mar', 'Nis', 'May', 'Haz', 'Tem', 'Ağt', 'Eyl', 'Ekm', 'Ksm', 'Ara'],
      days: ['Pazar', 'Pazartesi', 'Salı', 'Çarşamba', 'Perşembe', 'Cuma', 'Cumartesi'],
      shortDays: ['Pazar', 'Pazartesi', 'Salı', 'Çarşamba', 'Perşembe', 'Cuma', 'Cumartesi'],
      toolbar: {
        download: 'SVG Formatında İndir',
        selection: 'Büyüteç',
        selectionZoom: 'Yakınlaştırma Seçin',
        zoomIn: 'Yakınlaştır',
        zoomOut: 'Uzaklaştır',
        pan: 'Panning',
        reset: 'Sıfırla',
      }
    }
  }]
}`

**Comment by ozanerturk** [comment]
reponun forkunu alarak gerekli güncelleştirmeyi yapıp pull request gönderebilirsin review sonrası merge çıkabilirim
