### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by ozanerturk** [ozanerturk/covid19-turkey-api#13]
Şu an websitesinin mobil görüntüsü rezalet 
![image](https://user-images.githubusercontent.com/15703627/79237320-b10ecf80-7e76-11ea-8c27-b518cf8484e1.png)

'Bugün' tablosu mobil'de dikey gösterilebilir. 
Grafikler, mobilde her satıra bir tane gelecek şekilde yapılandırılabilir.
Grafikler, mobilde chartların label'ları ve değerleri gizlenerek sadeleştirilebilir.   

Responsive olması gerek.

**Comment by hattapoglu** [comment]
@ozanerturk selam Ozan. Ben de elimden geldiğince projenize katkı sağlamak istiyorum. Responsive tasarım için bir şeyler yapıp commitledim. Kontrol edip dönüş yapabilir misin?

**Comment by ozanerturk** [comment]
https://github.com/ozanerturk/covid19-turkey-api/pull/17#issuecomment-616237154 pullrequest'e comment yaptım.
