### ISSUE TITLE
Grafiklerde uyumsuz arkaplan

### ISSUE THREAD

**Issue by ozanerturk** [ozanerturk/covid19-turkey-api#22]
![image](https://user-images.githubusercontent.com/15703627/85987609-81438280-b9f6-11ea-9854-95c277b6cd2b.png)

Arkaplanın şeffaf olması gerekiyor.
Problem kullanılan cdn linklerinden birinde olabilir, kodda herhangi bir değişiklik olmadığı halde bir süre sonra bozuldu.

**Comment by ramazanzor19** [comment]
#26 nolu PR a bakabilirsin
