### ISSUE TITLE
Data Error ICU 29 July 2020

### ISSUE THREAD

**Issue by eguidotti** [ozanerturk/covid19-turkey-api#25]
Hello @ozanerturk, great repository!
We are integrating your data in the [COVID-19 Data Hub](https://covid19datahub.io/).

I spot an error in the `icu` value today (29 July 2020). There is a weird value "%9,4" in the file:
https://raw.githubusercontent.com/ozanerturk/covid19-turkey-api/master/dataset/timeline.csv

Cheers,
--Emanuele

**Comment by ozanerturk** [comment]
Hi, thanks for the warning, I am fixing right ahead.

**Comment by ozanerturk** [comment]
![image](https://user-images.githubusercontent.com/15703627/88912535-10e38780-d268-11ea-9c75-8accc9bcbef1.png)
EN
![image](https://user-images.githubusercontent.com/15703627/88912673-4a1bf780-d268-11ea-8040-0374eadc7202.png)

It seems the government source decided to change the future :(  I'll think how can we fix this.

**Comment by eguidotti** [comment]
Thank you!

**Comment by ozanerturk** [comment]
I have fixed the problem by ignoring the values of totalIntensiveCare and totalIntubated becaues they wont be there anymore :(
This is really sad that they changed suddenly these features. But at least now it is not weird. I hope it helps 


[dataset.csv](https://raw.githubusercontent.com/ozanerturk/covid19-turkey-api/master/dataset/timeline.csv)

**Comment by eguidotti** [comment]
Thank you @ozanerturk for the very quick fix. 
Is it possible to substitute the missing values `"-"` with `""` or just leave them empty?
I'm asking because I believe it will be easier for most programs to automatically read missing values in the form `""` instead of `"-"`.
Otherwise I will update our script to make it work with `"-"`

**Comment by ozanerturk** [comment]
Yeah, your right, empty should be empty. I'll make it done.

**Comment by ozanerturk** [comment]
Done
