### ISSUE TITLE
Dil desteği 

### ISSUE THREAD

**Issue by ozanerturk** [ozanerturk/covid19-turkey-api#3]
Readme ingilizceye çevrilebilir.

**Comment by ozanerturk** [comment]
web uygulamasını da ingilizce desteği getirebiliriz.

**Comment by capan** [comment]
i18n gibi mi?

**Comment by ozanerturk** [comment]
Evet. Önyüzde doğrudan javascript ve html kullanıldı çok büyük bi kütüphane kullanmaya pek gerek yok gibi. Ufak bir mekanizma kurgulayıp dil desteği sağlanabilir diye düşünüyorum. localization json dosyaralı oluşturularak metin alanları localstorage'deki language bilgisine bakarak metin alanlarını güncelleyebilir.
