### ISSUE TITLE
Missing-value/ lag Problem

### ISSUE THREAD

**Issue by dilaramustecep** [ozanerturk/covid19-turkey-api#30]
Merhaba,

Uygulama çok güzel,tebrikler. 
2 Eylül verisi neden güncellenmedi acaba ?  Bir gün önceden mi geliyor veriler, yoksa durdu mu ?

Teşekkürler

**Comment by ozanerturk** [comment]
Geri dönüş için teşekkürler,
Görünen o ki bakanlık web sayfasının yerini değiştirmiş. Hızlı bir şekilde güncelleme çıkıp eksik dataları doldurmasını sağlayacağım.

Lag' problemi için de chart library'i canvas temelli bir kütüphane ile değiştirmeyi düşünüyorum ancak vakit bulamıyorum.

Katkıda bulunmak isterseniz kapımız her zaman açık 👍

**Comment by ozanerturk** [comment]
Kontrolleri yaptığımda farkettim ki bakanlık sonunda bir api çıkartmış güncel duruma api kanalı üzerinden erişebilirsiniz.
ben de bu repoyu o api'ye bakacak şekilde güncelleyeceğim
https://covid19.saglik.gov.tr/covid19api?getir=sondurum
