### ISSUE TITLE
API adresleri çalışmıyor.

### ISSUE THREAD

**Issue by yunussandikci** [ozanerturk/covid19-turkey-api#31]
Merhaba,
Projede kullanılan https://covid19.saglik.gov.tr/covid19api'a bağlı olan adresler artık verileri döndürmüyor. Bu sebeple Github Actions çalışıyor gibi görünüyor olsa da artık çalışmıyor.
Ne yazıkki, yeni API adreslerini de sitede bulamadım. Tek çare siteyi parse etmek gibi gözüküyor.

Teşekkürler!

**Comment by ozanerturk** [comment]
Bilgilendirme için çok teşekkür ederim. Eski yönteme geri dönelim o zaman :D Hayır yok bunlardan

**Comment by ozanerturk** [comment]
düzenleme yapıldı
