### ISSUE TITLE
bakanlığın isim değişikliğini uygulama

### ISSUE THREAD

**Issue by ozanerturk** [ozanerturk/covid19-turkey-api#33]
yeni vaka /hasta değişikliği ile birlikte api düzenlendi,
frontend'deki localizasyonların da düzenlenmesi gerekiyor

**Comment by enesflow** [comment]
Şu an başka bir api kullanıyorum ben.

edit: Ama onda da günlük test sayısı yok maalesef

**Comment by ozanerturk** [comment]
yok onları halletim ben şuan datasetler güncel, api'yi kapatmışlar tekrar web scarping metoduna döndürdüm. datasetlerde gerekli renaming işlemlerini gerçekleştirdim. fakat UI kısmını da düzenlemek gerekiyor biraz.

**Comment by enesflow** [comment]
Peki tekrar aktif olacak miıhttps://covid19.saglik.gov.tr/covid19api?getir=sondurum fln

**Comment by ozanerturk** [comment]
O api' bakanlığa ait, o yüzden emin değilim.

**Comment by enesflow** [comment]
Çok iyi birşey buldum. https://covid19.saglik.gov.tr/TR-66935/genel-koronavirus-tablosu.html sitesinin scriptinde geneldurumjson adında bir variable var. O da https://covid19.saglik.gov.tr/covid19api?getir=liste nin aynısı

**Comment by ozanerturk** [comment]
O tabloya bakmıyoruz bu repoda ama diğer verileri öyle çekiyoruz. Kullanım örneğine bakark sende elde edebilirsin
     https://github.com/ozanerturk/covid19-turkey-api/blob/767ca1cd5983fe08cf7c6a142e58d023e64c905b/index.js#L21

**Comment by fthaksu** [comment]
Merhaba, 25/11/2020 öncesi "cases" değeri null olmuş sanırım bu değişiklikten dolayı. Eski "hasta" verileri ile bunu merge etme gibi bir şey yapılabilir mi?

**Comment by ozanerturk** [comment]
Evet, bakanın dediğine göre bizimle vaka değil hasta bilgisi paylaşıyorlarmış onun için isim değişikliği oldu. Şimdi vaka bilgileri gelince değiştirildi.

**Comment by enesflow** [comment]
Ben de Python da hergün covid 19 vakalarını göndermek için Telegram Botu yaptım [kovidbot](https://github.com/EnxGitHub/kovidbot)
