### ISSUE TITLE
dataset.csv dosyasına veriler yüklenmemiş.

### ISSUE THREAD

**Issue by uozcan12** [ozanerturk/covid19-turkey-api#38]
Merhaba,
04 Temmuz 2021 tarihinden beri bazı sütunlarda veriler yüklenmemiş gözüküyor. Düzeltirseniz çok sevinirim.

**Comment by ozanerturk** [comment]
Merhaba, veri kaynağı olan https://covid19.saglik.gov.tr/ artık bu bilgileri paylaşmadığı için maalesef o verilere ulaşamıyoruz.
