### ISSUE TITLE
Günlük entübe ve yoğun bakım hesaplama

### ISSUE THREAD

**Issue by berkerol** [ozanerturk/covid19-turkey-api#4]
Sağlık bakanlığı sitesi günlük entübe ve yoğun bakım sayısını vermiyor ancak elimizdeki bilgilerle hesaplayabiliriz. Bugünkü toplam sayıdan bir önceki günün toplam sayısını çıkarırsak, bu ikisi için günlük sayıları elde edebiliriz.

**Comment by ozanerturk** [comment]
Doğru. önceki veriler için bir kes manual hesap yaparak verileri güncellemek gerekecektir. Bir clone alıp bu çalışmayı gerçekleştirebilirsin. Her şeyin uygun olduğunu düşündüğünde de pull request açabilirsin. Kontrol ederek master'a mergeleyebilirim. Nedersin ?

**Comment by berkerol** [comment]
Aslında bu şekilde hesaplamak yanlış olacak gibi. Ölen ve iyileşenlerin normal vakadan, yoğun bakımdan ve entübelerden eksilme oranlarını bilmiyoruz.
Yani yoğun bakım ve entübe için iki gün arasındaki fark = günlük artış - ölen ve iyileşenler.
Hesaplamanın başka bir yolu yoksa bu issue kapatabiliriz.

**Comment by ozanerturk** [comment]
Hmm... doğru söylüyorsun. pek çok olasılık var. hasta yoğunbakımdayken , entübeyken , yada yalnıca vaka iken vefat etmiş yada iyileşmiş olabilir. artışın veya azalışın hangi sebepten kaynaklandığını belirlemek zor. Dediğin gibi yapıp bu issue'yu kapatacağım ama aklımızd da bulunsun belki hastalığın seyiri ile alakalı yüzdesel bir grafik de çizdirebiliriz. Teşekkürler.
